---
title: "9.	Objekte im Viewport Display transformieren"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div class="marginnote"> Befehle für Transformationen </div>

Statt mit der Sidebar können Objekte auch direkt im Viewport Display transformiert werden. Sobald ein – oder auch mehrere Objekte – ausgewählt sind, lassen sich die Objekte direkt im Viewport mittels der folgenden Befehle transformieren:

*   Position: 	<kbd>G</kbd> («Grab»)
*   Rotation: 	<kbd>R</kbd>
*   Skalierung:	<kbd>S</kbd>

# Poistion
<div class="marginnote"> Objekte bewegen mittels <kbd>G<kbd> </div>

Durch das Drücken der Taste G lässt sich ein ausgewähltes Objekt mit der Maus im Raum verschieben. Blender aktualisiert dabei parallel die Position des Objektes in der Sideview, so dass diese klar nachvollziehbar ist.

<div class="marginnote"> Bewegung entlang einer Achse </div>

Es ist auch im Viewport möglich ein Objekt nur in eine Achse zu bewegen. Hierfür wird nachdem Drücken der Taste <kbd>G</kbd> die Taste für die entsprechende Achse festgelegt (<kbd>X</kbd>, <kbd>Y</kbd> oder <kbd>Z</kbd>). Der farbige Strich im Viewport Display, welcher die entsprechende Achse markiert, leuchtet dadurch heller auf. Wenn die Maus nun bewegt wird, bewegt sich das Objekt lediglich entlang dieser Achse. Um die Bewegung zu beenden oder zu bestätigen, wird entweder die linke Maustaste oder <kbd>Enter</kbd> gedrückt. Dadurch wird der Befehle bestätigt. Um die Transformation abzubrechen kann die rechte Maustaste oder <kbd>Esc</kbd> gedrückt werden. Das Objekt wird dadurch wieder in seine Ursprungsposition zurückgestellt.

<div class="marginnote"> Bewegung entlang einer Achse sperren </div>

Es ist auch möglich zwei Achsen gleichzeitig für eine Bewegung auszuwählen. Hierfür wird die Bewegung entlang einer Achse gesperrt, so dass nur die beiden anderen Achsen für eine Bewegung freigegeben werden. Hierfür wird die Taste <kbd>Shift</kbd> in Kombination mit der Taste für die zu sperrende Ache (<kbd>X</kbd>, <kbd>Y</kbd> oder <kbd>Z</kbd>) gedrückt. Wenn ein Objekt also lediglich entlang der X- und der Y-Achse bewegt werden soll, aber die Z-Achse nicht verändert werden soll, kann nach dem Drücken der Taste <kbd>G</kbd> bei gedrückter <kbd>Shift</kbd> Taste die Z-Achse mittels der Taste <kbd>Z</kbd> gesperrt werden.

<div class="marginnote"> Bewegung mittels Zahlen präzise angeben </div>

Statt mit der Maus, kann während des Bewegungsvorgangs eine Zahl eingegeben werden, um eine Bewegung zu quantifizieren. Soll ein Objekt etwa um 2 Meter entlang der X-Achse verschoben werden, so wird nach dem die Bewegung mittels der Taste <kbd>G</kbd> gestartet und mittels der Taste <kbd>X</kbd> auf die X-Achse festgelegt wird, die Taste <kbd>2</kbd> gedrückt, um die Bewegung auf 2 Meter festzulegen. Durch das Drücken der Taste <kbd>-</kbd> können auch negative Werte eingegeben werden, so dass die Bewegung in die entgegengesetzte Richtung geschieht. In der linken oberen Ecke des Viewport Displays wird dabei die entsprechende Zahl angezeigt. So lassen sich etwa auch Bewegungen auf Dezimalstellen eingeben und mittels der Zahlenangabe verfolgen.
Rotation

<div class="marginnote"> Objekte rotieren mittels <kbd>R</kbd> </div>

Um ein ausgewähltes Objekt mit der Maus zu rotieren, wird die Taste <kbd>R</kbd gedrückt. Wie auch bei der Bewegung lässt sich eine Transformation entlang einer Achse ansteuern, indem die Taste für die entsprechende Achse gedrückt wird (<kbd>X</kbd>, <kbd>Y</kbd> oder <kbd>Z</kbd>). Ebenso lässt sich eine Achse für die Rotation sperren, indem sie die entsprechende Taste für diese Achse bei gedrückter <kbd>Shift</kbd> Taste gedrückt wird.
Wenn nun also ein Objekt entlang der Z-Achse rotiert werden soll, wird zunächst das entsprechende Objekt ausgewählt und anschliessend die Taste <kbd>R</kbd> für die den Befehl der Rotation gedrückt. Indem die Taste <kbd>Z</kbd> anschliessend gedrückt wird, lässt sich das Objekt nun lediglich entlang der Z-Achse rotieren. Während der Rotation verändert sich die Form der Maus und sie ist mit einem Strich zu dem Punkt, um den die Rotation erfolgt, verbunden. In der Regel handelt es sich dabei um den Ursprung des Objektes. Wie wir später sehen werden, kann die Rotation im Viewport Display auch hinsichtlich anderer Punkte im Raum erfolgen.

<div class="marginnote"> Präzise Rotation mittels Zahlen </div>

Auch während der Rotation kann mit der Eingabe von Zahlen gearbeitet werden. Um ein Objekt etwa um 45° entlang der Z-Achse zu drehen, wird nach dem Start der Rotation mittels der Taste <kbd>R</kbd> und der Festlegung der Z-Achse mit der Taste <kbd>Z</kbd> die Zahl 45 mittels der Tasten <kbd>45</kbd> eingegeben. Auch hier lässt sich die Richtung umkehren, indem die Taste <kbd>-</kbd> gedrückt wird.

# Scale

<div class="marginnote"> Objekte Skalieren mittels <kbd>S</kbd> </div>

Um ein ausgewähltes Objekt mit der Maus zu skalieren, wird die Taste <kbd>S</kbd> gedrückt. Wie auch bei der Bewegung und der Rotation lässt sich eine Transformation entlang einer einzelnen Achse ansteuern, indem die Taste für die entsprechende Achse gedrückt wird (<kbd>X</kbd>, <kbd>Y</kbd> oder <kbd>Z</kbd>). Ebenso lässt sich eine Achse für die Rotation sperren, indem sie die entsprechende Taste für diese Achse bei gedrückter <kbd>Shift</kbd> Taste gedrückt wird.

<div class="marginnote"> Skalierung entlang einer Achse </div>

Um ein Objekt nur entlang der X-Achse zu vergrössern oder zu verkleinern, so wird nach der Auswahl des Objektes die Taste <kbd>S</kbd> gedrückt, um mit der Skalierung zu starten. Anschliessend kann durch das Drücken der Taste <kbd>X</kbd> festgelegt werden, dass die Transformation lediglich entlang der X-Achse vollzogen werden soll. Während der Skalierung verändert sich der Maus-Cursor ebenfalls. Zudem ist er mittels eines Striches zu dem Punkt verbunden, zu dem hin sich die Skalierung orientiert. Wird die Maus näher zu diesem Punkt bewegt verkleinert sich das Objekt, wenn die Maus zu diesem Punkt entfernt wird, vergrössert sich das Objekt.

<div class="marginnote"> Präzise Skalierung mittels Zahlen </div>

Die Skalierung kann mittels Zahleneingaben ebenfalls sehr genau vorgenommen werden. Um ein Objekt etwa in seiner Grösse zu verdoppeln kann nach dem Start der Transformation mittels der Taste <kbd>S</kbd> die Zahl <kbd>2</kbd> eingegeben werden. Dadurch wird das Objekt um den Faktor 2 vergrössert. Auch hier lässt sich ein negativer Wert mittels der Taste <kbd>-</kbd> festlegen. Dies führt dazu, dass das Objekt durch seinen Bezugspunkt in die andere Richtung hindurch skaliert und gespiegelt wird. Bei symmetrischen Objekten führt dies allerdings zu keinem bemerkbaren Unterschied, allerdings schon bei nicht-symmetrischen Objekten.

####### ANIMATION 4 #########


# Übung 4: Objekttransformationen

## Übung 4.1 

Skalieren Sie einen Würfel entlang der X-Achse auf seine halbe Grösse

## Übung 4.2 

Bilden sie die Rotation und Skalierung des abgebildeten Objekts auf der richtigen Position nach.

 
::: {.remember  data-latex="{remember}"}
 
# Merke…

*   Mittels der Tasten <kbd>G</kbd>, <kbd>R</kbd> und <kbd>S</kbd> lassen sich Objekte auch im Viewport Display bewegen, rotieren und skalieren
*   Mittels der Eingabe von Zahlen können Bewegungen, Rotationen und Skalierungen genau vorgenommen werden.
*   Mittels der Tasten <kbd>X</kbd>, <kbd>Y</kbd> und <kbd>Z</kbd> können Transformationen auf eine Achse festgelegt werden.
*   Mittels der Tasten <kbd>X</kbd>, <kbd>Y</kbd> und <kbd>Z</kbd> bei gedrückter ƒ Taste können Transformationen auf der entsprechenden Achse unterbunden werden.

:::